### ISSUE TITLE
Node 20 upgrade

### ISSUE THREAD

**Issue by mrmeyers99** [tony84727/changed-file-filter#43]
I'm getting the following on my PR.  Can you please upgrade node?

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tony84727/changed-file-filter@v0.2.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by tony84727** [comment]
👌 Released v0.2.3 that runs on node 20. Should address the deprecation issue.

**Comment by mrmeyers99** [comment]
Thanks for the quick response!
